"""Optional Numba-accelerated Fermi imitation kernel.

Activated by setting USE_NUMBA=1 in the environment.
Uses parallel=False for joblib compatibility; benchmark before enabling prange.

Random numbers are pre-generated by the caller's numpy Generator and passed in,
keeping the RNG state in Python and letting Numba fuse the computation loop.
"""

import numpy as np
from numba import njit


@njit(parallel=False, cache=True)
def _fermi_jit(
    strategy: np.ndarray,  # (L, L) int8
    phi: np.ndarray,  # (L, L) float32
    beta: float,
    rand_dir: np.ndarray,  # (L, L) uint8 in {0,1,2,3}
    rand_acc: np.ndarray,  # (L, L) float32 in [0, 1)
) -> np.ndarray:
    """Inner JIT loop: fused direction-pick + Fermi accept (no Python overhead)."""
    L = strategy.shape[0]
    s_new = strategy.copy()

    for i in range(L):
        for j in range(L):
            d = rand_dir[i, j]
            if d == 0:
                ni, nj = (i - 1 + L) % L, j
            elif d == 1:
                ni, nj = (i + 1) % L, j
            elif d == 2:
                ni, nj = i, (j + 1) % L
            else:
                ni, nj = i, (j - 1 + L) % L

            diff = phi[ni, nj] - phi[i, j]
            # Clip prevents overflow in exp
            if diff > 30.0:
                fermi_p = 1.0
            elif diff < -30.0:
                fermi_p = 0.0
            else:
                fermi_p = 1.0 / (1.0 + np.exp(-beta * diff))

            if rand_acc[i, j] < fermi_p:
                s_new[i, j] = strategy[ni, nj]

    return s_new


def fermi_step_numba(
    strategy: np.ndarray,
    phi: np.ndarray,
    beta: float,
    rng: "np.random.Generator",
) -> np.ndarray:
    """
    Drop-in replacement for fermi_step_numpy using a Numba JIT inner loop.
    Random numbers are generated by the numpy Generator (same signature).
    """
    L = strategy.shape[0]
    rand_dir = rng.integers(0, 4, size=(L, L), dtype=np.uint8)
    rand_acc = rng.random((L, L), dtype=np.float32)
    return _fermi_jit(strategy, phi, beta, rand_dir, rand_acc)
