[project]
name = "abm-notebooks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jupyter",
    "notebook",
    "pywinpty==2.0.13; sys_platform == 'win32'",
    "setuptools",
    "mesa",
    "ipynb",
    "axelrod",
    "statsmodels",
    "salib",
    "pandas",
    "numpy",
    "matplotlib",
]
